# Generated by Django 4.2.5 on 2023-11-16 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hmi", "0076_displayvalueoptiontemplate_transformdata_and_more"),
        ("pyscada", "0105_edit_generic_device_protocol"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransformDataMeanAndDivByVar",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_value_option",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hmi.displayvalueoption",
                    ),
                ),
                (
                    "variable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pyscada.variable",
                    ),
                ),
            ],
        ),
    ]
